spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.104:3306/bili_memberdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: kirito
    password: kirito486
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.42:8848
  application:
    name: bili-member
  redis:
    host: 192.168.56.42

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:dao/*.xml
    - classpath:com/**/mapper/*.xml
server:
  port: 8085
  servlet:
    context-path: /apix/member
push-pull-point:
  1000000