spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bili_memberdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: kirito486
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: bili-search
  redis:
    host: 192.168.56.42
  elasticsearch:
    url: 192.168.56.42

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:dao/*.xml
    - classpath:com/**/mapper/*.xml
server:
  port: 8083
  servlet:
    context-path: /apix/search