server:
  port: 8081
  servlet:
    context-path: /apix/video
spring:
  application:
    name: bili-video
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.104:3306/bili_videodb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: kirito
    password: kirito486
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.42:8848
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 256MB
  redis:
    host: 192.168.56.42
minio:
  endpoint: http://192.168.56.42:9000
  bucket: video
  access-key: uploader
  access-secret: kirito486

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:dao/*.xml
    - classpath:com/**/mapper/*.xml

ffpmeg:
  path:
    temp-path: "/dash/tmp/"
    base-path: "dash/data/"
