spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.42:8848
    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            #是否允许cookie跨域  true允许
#            allowCredentials: true
#            #允许跨域的url * 则允许全部
#            allowedOriginPatterns: '*'
#            # 允许跨域的方法 * 则全部
#            allowedMethods: '*'
#            # 跨域预检时间
#            maxAge: 180
      routes:
        - id: video-route
          uri: lb://bili-video
          predicates:
            - Path=/apix/video/**
        - id: auth-route
          uri: lb://bili-auth
          predicates:
            - Path=/apix/auth/**
        - id: search-route
          uri: lb://bili-search
          predicates:
            - Path=/apix/search/**
        - id: member-route
          uri: lb://bili-member
          predicates:
            - Path=/apix/member/**
        - id: moment-route
          uri: lb://bili-moment
          predicates:
            - Path=/apix/moment/**
        - id: thumbup-route
          uri: lb://bili-thumbup
          predicates:
            - Path=/apix/thumbup/**
        - id: reply-route
          uri: lb://bili-reply
          predicates:
            - Path=/apix/reply/**
        - id: danmaku-route
          uri: lb://bili-danmaku
          predicates:
            - Path=/apix/danmaku/**
  application:
    name: bili-gateway
server:
  port: 8090
