spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            #是否允许cookie跨域  true允许
#            allowCredentials: true
#            #允许跨域的url * 则允许全部
#            allowedOriginPatterns: '*'
#            # 允许跨域的方法 * 则全部
#            allowedMethods: '*'
#            # 跨域预检时间
#            maxAge: 180
      routes:
        - id: video-route
          uri: lb://bili-video
          predicates:
            - Path=/apix/video/**
        - id: auth-route
          uri: lb://bili-auth
          predicates:
            - Path=/apix/auth/**
        - id: search-route
          uri: lb://bili-search
          predicates:
            - Path=/apix/search/**
        - id: member-route
          uri: lb://bili-member
          predicates:
            - Path=/apix/member/**
  application:
    name: bili-gateway
server:
  port: 8090
