spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.104:3306/bili_memberdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: kirito
    password: kirito486
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.42:8848
  application:
    name: bili-moment
  redis:
    host: 192.168.56.42
  kafka:
    bootstrap-servers: 192.168.56.42:9092
    producer:
      retries: 3
    consumer:
      group-id: moment-timeline-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 200
    listener:
      type: batch
      concurrency: 3

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:dao/*.xml
    - classpath:com/**/mapper/*.xml
server:
  port: 8084
  servlet:
    context-path: /apix/moment
push-pull-point:
  1000000